CREATE EXTENSION IF NOT EXISTS timescaledb;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE IF NOT EXISTS blocks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  height BIGINT NOT NULL,
  hash VARCHAR(80) NOT NULL,
  parent_hash VARCHAR(80) NOT NULL,
  state_root VARCHAR(80) NOT NULL,
  extrinsics_root VARCHAR(80) NOT NULL,
  spec_version INTEGER NOT NULL,
  timestamp TIMESTAMPTZ NOT NULL,
  extrinsic_count INTEGER NOT NULL DEFAULT 0,
  event_count INTEGER NOT NULL DEFAULT 0,
  is_finalized BOOLEAN NOT NULL DEFAULT FALSE,
  metadata JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS blocks_height_unique ON blocks (height);
CREATE UNIQUE INDEX IF NOT EXISTS blocks_hash_unique ON blocks (hash);
CREATE INDEX IF NOT EXISTS blocks_timestamp_idx ON blocks (timestamp);

CREATE TABLE IF NOT EXISTS accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  address VARCHAR(128) NOT NULL,
  label TEXT,
  description TEXT,
  first_seen_block_height BIGINT,
  last_seen_block_height BIGINT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS accounts_address_unique ON accounts (address);

CREATE TABLE IF NOT EXISTS extrinsics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  block_id BIGINT NOT NULL REFERENCES blocks(id),
  extrinsic_index INTEGER NOT NULL,
  extrinsic_id VARCHAR(64) NOT NULL,
  signer_address VARCHAR(128),
  section VARCHAR(64) NOT NULL,
  method VARCHAR(64) NOT NULL,
  args_json JSONB,
  success BOOLEAN NOT NULL DEFAULT TRUE,
  fee NUMERIC(38, 0),
  hash VARCHAR(80),
  timestamp TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS extrinsics_extrinsic_id_unique ON extrinsics (extrinsic_id);
CREATE INDEX IF NOT EXISTS extrinsics_block_id_idx ON extrinsics (block_id);
CREATE INDEX IF NOT EXISTS extrinsics_signer_idx ON extrinsics (signer_address);

CREATE TABLE IF NOT EXISTS events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  block_id BIGINT NOT NULL REFERENCES blocks(id),
  extrinsic_id VARCHAR(64),
  event_index INTEGER NOT NULL,
  event_id VARCHAR(64) NOT NULL,
  phase VARCHAR(32),
  section VARCHAR(64) NOT NULL,
  method VARCHAR(64) NOT NULL,
  data_json JSONB,
  timestamp TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS events_event_id_unique ON events (event_id);
CREATE INDEX IF NOT EXISTS events_block_id_idx ON events (block_id);
CREATE INDEX IF NOT EXISTS events_extrinsic_id_idx ON events (extrinsic_id);

CREATE TABLE IF NOT EXISTS transfers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  extrinsic_id VARCHAR(64),
  event_id VARCHAR(64),
  from_address VARCHAR(128),
  to_address VARCHAR(128),
  amount_rao NUMERIC(38, 0) NOT NULL,
  amount_tao NUMERIC(38, 9) NOT NULL,
  block_height BIGINT NOT NULL,
  timestamp TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS transfers_event_id_idx ON transfers (event_id);
CREATE INDEX IF NOT EXISTS transfers_from_address_idx ON transfers (from_address);
CREATE INDEX IF NOT EXISTS transfers_to_address_idx ON transfers (to_address);
CREATE INDEX IF NOT EXISTS transfers_block_height_idx ON transfers (block_height);

CREATE TABLE IF NOT EXISTS sync_state (
  key VARCHAR(64) PRIMARY KEY,
  value TEXT NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

